// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var addLicense, fs, readFile;
  fs = require('fs');
  addLicense = require('./license');
  readFile = function (filePath) {
    var buffer;
    buffer = fs.readFileSync(filePath);
    return buffer.toString();
  };
  module.exports = function (dir, workingDir, config) {
    var license;
    license = readFile('' + workingDir + '/LICENSE');
    if (null != license)
      return addLicense(dir, license, null != config ? config.license : void 0);
  };
}.call(this);
