// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var addLicense, bumpVersion, shrinkwrap, updateChangelog;
  bumpVersion = require('./version');
  shrinkwrap = require('./shrinkwrap');
  addLicense = require('./license');
  updateChangelog = require('./changelog');
  module.exports = function (directory, version, config) {
    var nextVersion;
    if (null == config)
      config = {};
    nextVersion = bumpVersion(directory, version);
    return shrinkwrap(directory, function () {
      addLicense(directory, config.license);
      return updateChangelog(nextVersion);
    });
  };
}.call(this);
