// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var fs, getNextVersion, semver, write;
  fs = require('fs');
  semver = require('semver');
  getNextVersion = function (currentVersion, versionOption) {
    if (versionOption.indexOf('.') > -1) {
      return versionOption;
    } else {
      return semver.inc(currentVersion, versionOption);
    }
  };
  write = function (filePath, object) {
    var output;
    output = JSON.stringify(object, null, 2);
    return fs.writeFileSync(filePath, output);
  };
  module.exports = function (directory, versionOption) {
    var currentVersion, nextVersion, packageJson, packagePath;
    packagePath = '' + directory + '/package.json';
    packageJson = require(packagePath);
    currentVersion = packageJson.version;
    nextVersion = getNextVersion(currentVersion, versionOption);
    packageJson.version = nextVersion;
    write(packagePath, packageJson);
    return console.log('Updated package to ' + nextVersion);
  };
}.call(this);
