// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var cli, command, config, directory, npub, option;
  npub = require('./index');
  cli = function (command, option, directory, config) {
    if (command === 'prep') {
      if (!(null != option)) {
        console.log('<version> required for command: prep');
        process.exit(2);
      }
      return npub.prep(directory, option, config);
    }
    if (command === 'publish')
      return npub.publish(directory, config);
    return console.log('invalid command: ' + command);
  };
  command = process.argv[2];
  option = process.argv[3];
  directory = process.cwd();
  config = require('' + directory + '/package.json').publishConfig;
  if (null != config) {
    delete config.registry;
    delete config.tag;
  }
  if (!(null != command)) {
    console.log('command required');
    process.exit(1);
  }
  cli(command, option, directory, config);
}.call(this);
