// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var log;
  log = function (message) {
    return console.log('[npub] ' + message);
  };
  log.error = function (message) {
    return console.error('[npub] ' + message);
  };
  module.exports = log;
}.call(this);
