// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var debug, Git;
  debug = require('debug')('clean-stage');
  Git = require('./git');
  module.exports = function (dir, callback) {
    var git;
    git = Git(dir);
    return git.isClean(function (isClean) {
      var err;
      debug('isClean: ' + isClean);
      if (!isClean)
        err = new Error('git status at ' + git.dir + ' is not clean');
      return callback(err);
    });
  };
}.call(this);
