// Generated by CoffeeScript 1.9.1
var Git, debug;

debug = require('debug')('clean-stage');

Git = require('./git');

module.exports = function(dir, callback) {
  var git;
  git = Git(dir);
  return git.isClean(function(isClean, dirtyFiles) {
    var err;
    debug("isClean: " + isClean);
    if (!isClean) {
      err = new Error("git status at " + git.dir + " is not clean.\nUncommitted file changes are:\n" + dirtyFiles + "\"");
    }
    return callback(err);
  });
};
