// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var git;
  git = require('./git');
  module.exports = function (dir, callback) {
    return git.isClean(dir, function (isClean) {
      if (!isClean)
        callback(new Error('git status at ' + dir + ' is not clean'));
      return callback();
    });
  };
}.call(this);
