// Generated by CoffeeScript 2.0.0-beta7
module.exports = function (git, callback) {
  return git.isClean(function (isClean) {
    if (!isClean)
      callback(new Error('git status at ' + git.dir + ' is not clean'));
    return callback();
  });
};
