// Generated by CoffeeScript 2.0.0-beta7
module.exports = function (git, version, callback) {
  return git.commit('v' + version, function (success) {
    if (!success) {
      console.error('[npub] failed to commit changes');
      process.exit(1);
    }
    return callback();
  });
};
