// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var debug;
  debug = require('debug')('commit-changes');
  module.exports = function (git, version, callback) {
    debug('v' + version);
    return git.commit('v' + version, function (success) {
      debug('status: ' + success);
      if (!success) {
        callback(new Error('failed to commit changes'));
        return;
      }
      return callback();
    });
  };
}.call(this);
