// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var editor;
  editor = require('editor');
  module.exports = function (filePath, callback) {
    return editor(filePath, function (exitCode) {
      if (exitCode !== 0) {
        console.error('[npub] exited editor with ' + exitCode + '; aborting');
        process.exit(exitCode);
      }
      return callback();
    });
  };
}.call(this);
