// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var debug, editor;
  editor = require('editor');
  debug = require('debug')('editor');
  module.exports = function (filePath, callback) {
    debug(filePath);
    return editor(filePath, function (exitCode) {
      debug('status: ' + exitCode);
      if (exitCode !== 0) {
        callback(new Error('editor exited editor with ' + exitCode + '; aborting'));
        return;
      }
      return callback();
    });
  };
}.call(this);
