// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var exec, gitCommand;
  exec = require('child_process').exec;
  gitCommand = function (dir, command, callback) {
    var options;
    options = { cwd: dir };
    return exec('git ' + command, options, callback);
  };
  module.exports = {
    isClean: function (dir, callback) {
      return gitCommand(dir, 'diff --exit-code', function (error, stdout, stderror) {
        return callback(!error);
      });
    },
    commit: function (dir, message, callback) {
      return gitCommand(dir, " add --all ; git commit -m '" + message + "'", function (error, stdout, stderror) {
        return callback(!error);
      });
    },
    diffSinceLastTag: function (dir, callback) {
      return gitCommand(dir, 'log --oneline $(git describe --tags --abbrev=0)..HEAD', function (error, stdout, stderr) {
        if (null != error)
          throw error;
        return callback(stdout);
      });
    },
    tag: function (dir, tag, callback) {
      console.log('tagging?');
      return gitCommand(dir, 'tag -a ' + tag + ' -m ' + tag, function (error, stdout, stderror) {
        if (null != error)
          throw error;
        console.log(stdout);
        console.log(stderror);
        return callback();
      });
    }
  };
}.call(this);
