// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var exec;
  exec = require('child_process').exec;
  module.exports = function (dir) {
    var options;
    options = { cwd: dir };
    return {
      dir: dir,
      isClean: function (callback) {
        return exec('git diff --exit-code', options, function (error, stdout, stderror) {
          return callback(!error);
        });
      },
      commit: function (message, callback) {
        return exec("git add CHANGELOG.md package.json && git commit -m '" + message + "'", options, function (error, stdout, stderror) {
          return callback(!error);
        });
      },
      diffSinceLastTag: function (callback) {
        return exec('git log --oneline $(git describe --tags --abbrev=0)..HEAD', options, function (error, stdout, stderr) {
          return callback(error, stdout);
        });
      },
      tag: function (tag, callback) {
        return exec('git tag -a ' + tag + ' -m ' + tag, options, function (error, stdout, stderror) {
          return callback(error);
        });
      },
      branch: function (callback) {
        return exec('git rev-parse --abbrev-ref HEAD', options, function (error, stdout, stderr) {
          return callback(error, stdout);
        });
      },
      push: function (branch, callback) {
        return exec('git push origin ' + branch, options, function (error, stdout, stderror) {
          return callback(error);
        });
      },
      pushTag: function (tag, callback) {
        return exec('git push origin tag ' + tag, options, function (error, stdout, stderror) {
          return callback(error);
        });
      }
    };
  };
}.call(this);
