// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var changelog, commitChanges, endIf, ensureCleanStage, fs, git, license, npm, openEditor, prompt, updateVersion;
  fs = require('fs');
  license = require('./license');
  ensureCleanStage = require('./clean-stage');
  changelog = require('./changelog');
  openEditor = require('./editor');
  updateVersion = require('./version');
  commitChanges = require('./commit-changes');
  npm = require('./npm');
  git = require('./git');
  prompt = require('./prompt');
  endIf = function (exitCodeOrError, message) {
    if (!(null != exitCodeOrError))
      return;
    if (exitCodeOrError instanceof Error) {
      console.error('[npub] ' + exitCodeOrError.message);
      return process.exit(1);
    } else {
      if (exitCodeOrError === 0)
        return;
      if (null != message)
        message;
      else
        message = 'exited with ' + exitCodeOrError;
      console.error('[npub] ' + message);
      return process.exit(exitCodeOrError);
    }
  };
  module.exports = function (dir, version, config) {
    return ensureCleanStage(dir, function (error) {
      endIf(error);
      license(dir, config);
      return ensureCleanStage(dir, function (error) {
        endIf(error);
        return npm.test(dir, function (error) {
          endIf(error);
          return changelog.build(dir, function (tempChangelog) {
            var tempChangelogPath;
            tempChangelogPath = changelog.write(tempChangelog);
            return openEditor(tempChangelogPath, function (error) {
              if (null != error) {
                fs.unlinkSync(tempChangelogPath);
                endIf(error);
              }
              changelog.update(dir, tempChangelogPath);
              updateVersion(dir, version);
              return commitChanges(dir, version, function () {
                var tag;
                tag = 'v' + version;
                return git.tag(dir, tag, function () {
                  return prompt(version, function (error) {
                    endIf(error);
                    return git.push(dir, function () {
                      return git.pushTag(dir, tag, function () {
                        return npm.publish(dir, function (error) {
                          endIf(error);
                          return console.log('success!');
                        });
                      });
                    });
                  });
                });
              });
            });
          });
        });
      });
    });
  };
}.call(this);
