// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var Changelog, commitChanges, debug, endIf, ensureCleanStage, fs, Git, license, Npm, openEditor, prompt, updateVersion;
  fs = require('fs');
  license = require('./license');
  ensureCleanStage = require('./clean-stage');
  Changelog = require('./changelog');
  openEditor = require('./editor');
  updateVersion = require('./version');
  commitChanges = require('./commit-changes');
  Npm = require('./npm');
  Git = require('./git');
  prompt = require('./prompt');
  endIf = function (exitCodeOrError, message) {
    if (!(null != exitCodeOrError))
      return;
    if (exitCodeOrError instanceof Error) {
      console.error('[npub] ' + exitCodeOrError.message);
      return process.exit(1);
    } else {
      if (exitCodeOrError === 0)
        return;
      if (null != message)
        message;
      else
        message = 'exited with ' + exitCodeOrError;
      console.error('[npub] ' + message);
      return process.exit(exitCodeOrError);
    }
  };
  debug = function (message) {
  };
  module.exports = function (dir, version, config) {
    var changelog, git, npm;
    git = Git(dir);
    npm = Npm(dir);
    changelog = Changelog(dir, git);
    return ensureCleanStage(git, function (error) {
      endIf(error);
      license(dir, config);
      debug('ensured license headers');
      return ensureCleanStage(git, function (error) {
        endIf(error);
        return npm.test(function (error) {
          endIf(error);
          debug('ran: npm test');
          return changelog.build(function (error, tempChangelog) {
            var tempChangelogPath;
            endIf(error);
            tempChangelogPath = changelog.write(tempChangelog);
            debug('temp changelog at: ' + tempChangelogPath);
            return openEditor(tempChangelogPath, function (error) {
              if (null != error) {
                fs.unlinkSync(tempChangelogPath);
                endIf(error);
              }
              changelog.update(tempChangelogPath);
              debug('updated changelog');
              updateVersion(dir, version);
              debug('updated version');
              return commitChanges(git, version, function () {
                var tag;
                debug('changes committed');
                tag = 'v' + version;
                return git.tag(tag, function (error) {
                  endIf(error);
                  debug('tagged: ' + tag);
                  return prompt(version, function (error) {
                    endIf(error);
                    return git.branch(function (error, branch) {
                      endIf(error);
                      debug('git branch: ' + branch);
                      return git.push(branch, function (error) {
                        endIf(error);
                        debug('git pushed');
                        return git.pushTag(tag, function (error) {
                          endIf(error);
                          debug('git tag "' + tag + '" pushed');
                          return npm.publish(function (error) {
                            endIf(error);
                            debug('published');
                            return console.log('success!');
                          });
                        });
                      });
                    });
                  });
                });
              });
            });
          });
        });
      });
    });
  };
}.call(this);
