// Generated by CoffeeScript 1.9.1
var debug, exec;

exec = require('child_process').exec;

debug = require("debug")("npm");

module.exports = function(dir, log) {
  var options;
  debug("initialized for: " + dir);
  options = {
    dir: dir
  };
  return {
    test: function(callback) {
      debug("test");
      return exec("npm test", options, function(error, stdout, stderr) {
        if (stdout != null) {
          log(stdout);
        }
        if (stderr != null) {
          log.error(stderr);
        }
        if (error != null) {
          callback(new Error("tests failed with exit code: " + error.code));
          return;
        }
        return callback();
      });
    },
    publish: function(callback) {
      debug("publish");
      return exec("npm publish", options, function(error, stdout, stderr) {
        if (stdout != null) {
          log(stdout);
        }
        if (stderr != null) {
          log.error(stderr);
        }
        if (error != null) {
          callback(new Error("tests failed with exit code: " + error.code));
          return;
        }
        return callback();
      });
    }
  };
};
