// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var debug, exec;
  exec = require('child_process').exec;
  debug = require('debug')('test');
  module.exports = function (dir, log, npm, testCommand, callback) {
    var options;
    debug('run');
    options = { dir: dir };
    if (testCommand) {
      debug('exec ' + testCommand);
      return exec(testCommand, options, function (error, stdout, stderr) {
        if (null != stdout)
          log(stdout);
        if (null != stderr)
          log.error(stderr);
        if (null != error) {
          callback(new Error('tests failed with exit code: ' + error.code));
          return;
        }
        return callback();
      });
    } else {
      return npm.test(callback);
    }
  };
}.call(this);
