// Generated by CoffeeScript 1.9.1
var debug, exec;

exec = require('child_process').exec;

debug = require("debug")("test");

module.exports = function(dir, log, npm, testCommand, callback) {
  var options;
  debug("run");
  options = {
    dir: dir
  };
  if (testCommand) {
    debug("exec " + testCommand);
    return exec(testCommand, options, function(error, stdout, stderr) {
      if (stdout != null) {
        log(stdout);
      }
      if (stderr != null) {
        log.error(stderr);
      }
      if (error != null) {
        callback(new Error("tests failed with exit code: " + error.code));
        return;
      }
      return callback();
    });
  } else {
    return npm.test(callback);
  }
};
