// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var debug, exec;
  exec = require('child_process').exec;
  debug = require('debug')('test');
  module.exports = function (dir, npm) {
    var options;
    debug('initialized for: ' + dir);
    options = { dir: dir };
    return function (testCommand, callback) {
      debug('run');
      if (testCommand) {
        debug('exec ' + testCommand);
        return exec(testCommand, options, function (error, stdout, stderr) {
          if (null != stdout)
            console.log(stdout);
          if (null != stderr)
            console.log(stderr);
          if (null != error) {
            callback(new Error('tests failed with exit code: ' + error.code));
            return;
          }
          return callback();
        });
      } else {
        return npm.test(callback);
      }
    };
  };
}.call(this);
