// Generated by CoffeeScript 2.0.0-beta7
void function () {
  var fs;
  fs = require('fs');
  module.exports = function (dir, version) {
    var filePath, packageJson;
    filePath = '' + dir + '/package.json';
    packageJson = require(filePath);
    packageJson.version = version;
    return fs.writeFileSync(filePath, JSON.stringify(packageJson, null, 2));
  };
}.call(this);
